# vim:fileencoding=utf-8:foldmethod=marker

env PATH=/Users/joe/.local/share/mise/shims:${PATH}

font_family MesloLGM Nerd Font Mono
font_size 14

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1
tab_title_template "{index}: {title}"

allow_remote_control yes
listen_on unix:/tmp/kitty

map cmd+k launch --type=overlay-main /Users/joe/.config/kitty/pick-repo.ts


# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
