os:
  edit: 'nvr --remote-wait {{filename}}'
  openLink: sh -c 'printf "\033]52;c;$(printf "%s" "{{link}}" | base64 -w 0)\a" > /dev/tty'
  copyToClipboardCmd: sh -c 'printf "\033]52;c;$(printf "%s" "{{text}}" | base64 -w 0)\a" > /dev/tty'

promptToReturnFromSubprocess: false

quitOnTopLevelReturn: true

notARepository: quit

git:
  overrideGpg: true
  pagers:
    - externalDiffCommand: "difft --color=always"

