[tools]
java = "21"
node = "24"
python = "3.13"
fzf = "0.72.0"
lazygit = "0.61.1"
lazydocker = "0.25.2"
sd = "1.1.0"
fd = "10.4.2"
pnpm = "11.0.6"
pi = "0.73.0"
go = "1.25.3"
rust = "1.95.0"
lua = "5.5.0"
lua-language-server = "3.18.2"
zig = "0.16.0"
zls = "0.16.0"
neovim = "0.12.2"
clang = "22.1.4"
ripgrep = "15.1.0"
