[tools]
node = "24"
python = "latest"
fzf = "latest"
lazygit = "latest"
lazydocker = "latest"
sd = "latest"
fd = "latest"
pnpm = "latest"
pi = "latest"
go = "latest"
rust = "latest"
lua-language-server = "latest"
zig = "latest"
zls = "latest"
neovim = "latest"
clang = "latest"
ripgrep = "latest"
difftastic = "latest"
tree-sitter = "latest"
harper-ls = "latest"
stylua = "latest"
clang-format = "latest"
uv = "latest"
gitleaks = "latest"
hyperfine = "latest"
cmake = "latest"
opencode = "latest"
"pipx:yq" = "latest"
"pipx:algokit" = "latest"
"pipx:mypy" = "latest"
"pipx:poetry" = "latest"
"pipx:neovim-remote" = "latest"
"pipx:mdformat" = "latest"
"npm:@vtsls/language-server" = "latest"
jq = "latest"
"cargo:circom-lsp" = "latest"
bat = "latest"

[settings]
minimum_release_age = "7d"
